// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_SistemaDeGestion.Data;

#nullable disable

namespace P2_SistemaDeGestion.Migrations
{
    [DbContext(typeof(SistemaDBContext))]
    partial class SistemaDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("P2_SistemaDeGestion.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApellidoPaterno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApellidoMaterno = "Gómez",
                            ApellidoPaterno = "Pérez",
                            Nombre = "Juan",
                            Telefono = "555-1234"
                        },
                        new
                        {
                            Id = 2,
                            ApellidoMaterno = "Martínez",
                            ApellidoPaterno = "López",
                            Nombre = "Ana",
                            Telefono = "555-5678"
                        },
                        new
                        {
                            Id = 3,
                            ApellidoMaterno = "Santos",
                            ApellidoPaterno = "Ramírez",
                            Nombre = "Luis",
                            Telefono = "555-8765"
                        },
                        new
                        {
                            Id = 4,
                            ApellidoMaterno = "Vega",
                            ApellidoPaterno = "Torres",
                            Nombre = "María",
                            Telefono = "555-4321"
                        },
                        new
                        {
                            Id = 5,
                            ApellidoMaterno = "Ruiz",
                            ApellidoPaterno = "Hernández",
                            Nombre = "Carlos",
                            Telefono = "555-2468"
                        });
                });

            modelBuilder.Entity("P2_SistemaDeGestion.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Marca");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "HP"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Lenovo"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Logitech"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "DELL"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Nike"
                        });
                });

            modelBuilder.Entity("P2_SistemaDeGestion.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMarca")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Producto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Portátil 15''",
                            Existencia = 10,
                            IdMarca = 1,
                            Nombre = "Laptop",
                            Precio = 12000m
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Mouse óptico",
                            Existencia = 50,
                            IdMarca = 2,
                            Nombre = "Mouse",
                            Precio = 250m
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Teclado mecánico",
                            Existencia = 30,
                            IdMarca = 3,
                            Nombre = "Teclado",
                            Precio = 800m
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Monitor 24''",
                            Existencia = 15,
                            IdMarca = 4,
                            Nombre = "Monitor",
                            Precio = 3500m
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Impresora láser",
                            Existencia = 8,
                            IdMarca = 4,
                            Nombre = "Impresora",
                            Precio = 2200m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
