// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_SistemaDeGestion.Data;

#nullable disable

namespace P2_SistemaDeGestion.Migrations.Producto
{
    [DbContext(typeof(ProductoContext))]
    [Migration("20251003060518_03102025Productos")]
    partial class _03102025Productos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("P2_SistemaDeGestion.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Producto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Portátil 15''",
                            Existencia = 10,
                            Nombre = "Laptop",
                            Precio = 12000m
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Mouse óptico",
                            Existencia = 50,
                            Nombre = "Mouse",
                            Precio = 250m
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Teclado mecánico",
                            Existencia = 30,
                            Nombre = "Teclado",
                            Precio = 800m
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Monitor 24''",
                            Existencia = 15,
                            Nombre = "Monitor",
                            Precio = 3500m
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Impresora láser",
                            Existencia = 8,
                            Nombre = "Impresora",
                            Precio = 2200m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
